# Generated by Django 5.1.1 on 2024-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comp', models.DateField(verbose_name='Fecha Compra')),
                ('producto', models.CharField(max_length=75, verbose_name='Producto')),
                ('kilogramo', models.IntegerField(verbose_name='kilogramo')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=75, verbose_name='Apellido')),
                ('DNI', models.CharField(max_length=12, verbose_name='DNI')),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hamburguesa', models.IntegerField(blank=True, null=True, verbose_name='hamburguesa')),
                ('lomo', models.IntegerField(blank=True, null=True, verbose_name='lomo')),
                ('chorizo', models.IntegerField(blank=True, null=True, verbose_name='chorizo')),
                ('cono_fritas', models.IntegerField(blank=True, null=True, verbose_name='cono_fritas')),
                ('milanesa', models.IntegerField(blank=True, null=True, verbose_name='milanesa')),
                ('pizza', models.IntegerField(blank=True, null=True, verbose_name='pizza')),
                ('agua_chica', models.IntegerField(blank=True, null=True, verbose_name='agua_chica')),
                ('agua_grande', models.IntegerField(blank=True, null=True, verbose_name='agua_grande')),
                ('cerveza_lata', models.IntegerField(blank=True, null=True, verbose_name='cerveza_lata')),
                ('cerveza_litro', models.IntegerField(blank=True, null=True, verbose_name='cerveza_litro')),
            ],
        ),
    ]
