# Generated by Django 5.1.1 on 2024-09-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarioDb',
            new_name='usuario',
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True, 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': True, 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='venta',
        ),
    ]
